# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(354, 517)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_login = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.verticalLayout.addWidget(self.lineEdit_login)
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.checkBox_toggle_password = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.checkBox_toggle_password.setFont(font)
        self.checkBox_toggle_password.setObjectName("checkBox_toggle_password")
        self.verticalLayout.addWidget(self.checkBox_toggle_password)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.lineEdit_url.setFont(font)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.verticalLayout.addWidget(self.lineEdit_url)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.lineEdit_name.setFont(font)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout.addWidget(self.lineEdit_name)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.spinBox_world_number = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_world_number.sizePolicy().hasHeightForWidth())
        self.spinBox_world_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.spinBox_world_number.setFont(font)
        self.spinBox_world_number.setMinimum(1)
        self.spinBox_world_number.setMaximum(9)
        self.spinBox_world_number.setObjectName("spinBox_world_number")
        self.horizontalLayout_2.addWidget(self.spinBox_world_number)
        self.label_worlds = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_worlds.setFont(font)
        self.label_worlds.setObjectName("label_worlds")
        self.horizontalLayout_2.addWidget(self.label_worlds)
        self.verticalLayout.addWidget(self.groupBox)
        self.checkBox_remember = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(10)
        self.checkBox_remember.setFont(font)
        self.checkBox_remember.setObjectName("checkBox_remember")
        self.verticalLayout.addWidget(self.checkBox_remember)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox.setSizePolicy(sizePolicy)
        self.horizontalGroupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout.setSpacing(30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_vote_cycle = QtWidgets.QRadioButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_vote_cycle.setFont(font)
        self.radioButton_vote_cycle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_vote_cycle.setChecked(True)
        self.radioButton_vote_cycle.setObjectName("radioButton_vote_cycle")
        self.horizontalLayout.addWidget(self.radioButton_vote_cycle)
        self.radioButton_vote_once = QtWidgets.QRadioButton(self.horizontalGroupBox)
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_vote_once.setFont(font)
        self.radioButton_vote_once.setChecked(False)
        self.radioButton_vote_once.setObjectName("radioButton_vote_once")
        self.horizontalLayout.addWidget(self.radioButton_vote_once)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.plainTextEdit_log.setFont(font)
        self.plainTextEdit_log.setReadOnly(True)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.verticalLayout.addWidget(self.plainTextEdit_log)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MMOTOP voting by antiss"))
        self.lineEdit_login.setPlaceholderText(_translate("MainWindow", "Логин VK"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Пароль VK"))
        self.checkBox_toggle_password.setText(_translate("MainWindow", "Показать пароль"))
        self.lineEdit_url.setPlaceholderText(_translate("MainWindow", "https://all.mmotop.ru/servers/1234"))
        self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "Введите логин/имя персонажа"))
        self.label_worlds.setText(_translate("MainWindow", "Выберите номер сервера/мира"))
        self.checkBox_remember.setText(_translate("MainWindow", "Запомнить?"))
        self.radioButton_vote_cycle.setText(_translate("MainWindow", "Голосовать раз в сутки"))
        self.radioButton_vote_once.setText(_translate("MainWindow", "Голосовать 1 раз"))
        self.pushButton_start.setText(_translate("MainWindow", "Старт"))
